apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: apereo-cas
    status: live
  name: apereo-cas
spec:
  replicas: ${apereo-cas-replicas}
  template:
    metadata:
      labels:
        app: apereo-cas
    spec:
      volumes:
        - name: apereo-cas-ssl
          secret:
            secretName: apereo-cas-ssl
        - name: apereo-cas-saml
          secret:
            secretName: apereo-cas-saml
      containers:
        - env:
            - name: HOSTNAME
              value: ${apereo-cas-server-host-name}
            - name: REGISTRY_DB_HOST
              value: ${apereo-cas-registry-db-host}
            - name: REGISTRY_DB_PORT
              value: "${apereo-cas-registry-db-port}"
            - name: REGISTRY_DB_NAME
              value: ${apereo-cas-registry-db-name}
            - name: REGISTRY_DB_USER
              value: ${apereo-cas-registry-db-user}
            - name: REGISTRY_DB_PASS
              value: ${apereo-cas-registry-db-pass}
            - name: MYSQL_VOICEAXIS_HOST
              value: ${mysql-voiceaxis-host}
            - name: MYSQL_VOICEAXIS_PORT
              value: "${mysql-voiceaxis-port}"
            - name: MYSQL_VOICEAXIS_USER
              value: ${mysql-voiceaxis-user}
            - name: MYSQL_VOICEAXIS_PASSWORD
              value: ${mysql-voiceaxis-password}
            - name: MYSQL_VOICEAXIS_DB
              value: ${mysql-voiceaxis-db}
            - name: TOKEN_SIGNING_KEY
              value: ${apereo-cas-token-signing-key}
            - name: TOKEN_ENCRYPT_KEY
              value: ${apereo-cas-token-encryption-key}
            - name: WEBFLOW_SIGNING_KEY
              value: ${apereo-cas-webflow-signing-key}
            - name: WEBFLOW_ENCRYPT_KEY
              value: ${apereo-cas-webflow-encryption-key}
            - name: TGC_SIGNING_KEY
              value: ${apereo-cas-tgc-signing-key}
            - name: TGC_ENCRYPT_KEY
              value: ${apereo-cas-tgc-encryption-key}
            - name: REGISTRY_SIGNING_KEY
              value: ${apereo-cas-registry-signing-key}
            - name: REGISTRY_ENCRYPT_KEY
              value: ${apereo-cas-registry-encryption-key}
            - name: TOMCAT_KEYSTORE_FILE
              value: ${apereo-cas-tomcat-keystore-file}
            - name: TOMCAT_KEYSTORE_TYPE
              value: ${apereo-cas-tomcat-keystore-type}
            - name: TOMCAT_KEYSTORE_PASS
              value: ${apereo-cas-tomcat-keystore-pass}
            - name: TOMCAT_KEY_PASS
              value: ${apereo-cas-tomcat-key-pass}
            - name: TOMCAT_KEY_ALIAS
              value: "${apereo-cas-tomcat-key-alias}"
          image: eng-kubes.dev.coredial.com:30122/apereo/cas:v5.4.2-20
          name: apereo-cas
          volumeMounts:
            - name: apereo-cas-ssl
              mountPath: /etc/cas/ssl
            - name: apereo-cas-saml
              mountPath: /etc/cas/saml
          command: ["/cas-overlay/bin/run-cas.sh"]
          ports:
            - containerPort: 8080
              name: http
            - containerPort: 8443
              name: https
